# Generated by Django 5.1.2 on 2024-12-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
