# Generated by Django 5.0.3 on 2024-12-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umms', '0002_food_is_new_food_is_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
